- name: jenkins gorup
  group:
    name: jenkins
    gid: 3666

- name: jenkins user
  user:
    name: jenkins
    uid: 3666
    group: jenkins

- name: jenkins home directory
  file:
    path: "{{ jenkins_home_directory }}"
    state: directory
    mode: 0777

- name: configure jenkins server
  docker_container:
    name: jenkins-master
    image: jenkins/jenkins
    state: started
    privileged: yes
    restart_policy: unless-stopped
    user: 3666:3666
    ports:
      - "8080:8080"
    volumes:
      - "{{ jenkins_home_directory  }}:/var/jenkins_home"
