- name: create update directory
  file:
    path: "{{ jenkins_home_directory }}/updates"
    state: directory
    owner: jenkins
    group: jenkins

- name: download current plugin updates
  get_url:
    url: http://updates.jenkins-ci.org/update-center.json
    dest: "{{ jenkins_home_directory }}/updates/default.json"
    owner: jenkins
    group: jenkins
    mode: 0440
  changed_when: false

- name: remove first and last line from json file
  replace:x
    path: "{{ jenkins_home_directory }}/updates/default.json"
    regexp: "1d;$d"

- name: install jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home_directory }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: present
    timeout: 30
    updates_expiration: 86400
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    with_dependencies: yes
  notify: restart jenkins
  with_items:
    - docker-plugin
    - blueocean
    - simple-theme-plugin
    - maven-plugin
    - maven-metadata-plugin
    - config-file-provider
    - pipeline-maven
    - pipeline-utility-steps
    - test-results-analyzer
    - show-build-parameters
    - external-monitor-job
    - active-directory
    - role-strategy
    - ansible
    - ansicolor
