- name: create update directory
  file:
    path: "{{ jenkins_home_directory }}/updates"
    state: directory
    owner: jenkins
    group: jenkins

- name: download current plugin updates
  get_url:
    url: http://updates.jenkins-ci.org/update-center.json
    dest: "{{ jenkins_home_directory }}/updates/default.json"
    owner: jenkins
    group: jenkins
    mode: 0440
  changed_when: false

- name: Remove first and last line from json file
  replace:
    path: "{{ jenkins_home_directory }}/updates/default.json"
    regexp: "1d;$d"

- name: install jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home_directory }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: "{{ jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    with_dependencies: "{{ jenkins_plugins_install_dependencies }}"
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins
